signup機能
shinonome-inc/backend-final-assignment-sora pull request #1
Opened 2023-08-30 01:48 UTC by NakaokaSora

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-09 00:53 UTC, TamanPG commented on accounts/models.py
>  # from django.db import models
不要なコメントは削除して大丈夫です！

2023-09-09 00:53 UTC, TamanPG commented on accounts/models.py
>  # class User(AbstractUser):
ここも

2023-09-09 01:31 UTC, TamanPG commented on templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
不要な文字列("base.htmlを継承"の所)は削除しておいてください！

2023-09-09 01:34 UTC, TamanPG requested changes
丁寧でよく書けています！
いくつか消し忘れがありましたのでそこだけ修正お願いいたします。

2023-09-10 00:11 UTC, TamanPG approved these changes

2023-09-12 04:42 UTC, Reiyamatsumoto commented
LGTM!!
次の機能の実装に進んでください！

2023-09-12 04:42 UTC, merged